name: Publish
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: 
      - publish

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  publish:
    uses: auditlogic/content-workflows/.github/workflows/publish-reusable.yml@main
    secrets: inherit
