name: Pull Request
on:
  pull_request:
    types:
      - labeled
      - synchronize
  pull_request_target:
    types:
      - labeled
      - synchronize

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  pull-request:
    uses: zerobias-org/devops/.github/workflows/pull-request-reusable.yml@new-workflow-tests
    secrets: inherit
    with:
      run-integration-tests: 'false'
